# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c3d992db54d292cbd450482513f040a706e839bdc1a7c7f1659e7a6d7c502fec64d51b620286f36c07b33f949ee9c72c5e855bb50aea63f90ebfab724af1215

test:
  secret_key_base: 6b3945dc268ad4b2bc5d99a9193f2e1158dfd7f5356f67106c29b85f1d457077bb922227e5bf8249d4cfcad5f7be14ca874816a784394b7ab39a8ba46ec84be4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
